### ISSUE TITLE
Issue with table folder names

### ISSUE THREAD

**Issue by tischi** [mobie/zebrafish-lm-datasets#5]
Branch: new-data-spec

The image source names do _not_ contain "membrane-" but the sub-folders for the tables do contain the "membrane-" prefix. Thus, the current code cannot find the tables as it assumes the subfolder name to be identical to the image source name.

ping @constantinpape

**Comment by constantinpape** [comment]
> Branch: new-data-spec

To avoid confusion: the brach is called `new-table-spec`

> 
> The image source names do _not_ contain "membrane-" but the sub-folders for the tables do contain the "membrane-" prefix. Thus, the current code cannot find the tables as it assumes the subfolder name to be identical to the image source name.

I think that's just a bug in the code and not in this repository. Because the name of the table folder should not matter, it only needs to be the same as in the "relativePath": https://github.com/mobie/zebrafish-lm-datasets/blob/new-table-spec/data/membrane/dataset.json#L28
